/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        display: ['"Young Serif"', 'serif'],
        body: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        cream: '#FAF7F2',
        parchment: '#F0EBE3',
        ink: '#1C1917',
        copper: {
          50: '#FFF8ED',
          100: '#FFEFD4',
          200: '#FFD9A3',
          300: '#FFBD67',
          400: '#FF9520',
          500: '#F97316',
          600: '#DD5E0A',
          700: '#B45309',
          800: '#92400E',
          900: '#713507',
        },
      },
      typography: (theme) => ({
        mill: {
          css: {
            '--tw-prose-body': theme('colors.stone.700'),
            '--tw-prose-headings': theme('colors.stone.900'),
            '--tw-prose-lead': theme('colors.stone.600'),
            '--tw-prose-links': theme('colors.copper.700'),
            '--tw-prose-bold': theme('colors.stone.900'),
            '--tw-prose-counters': theme('colors.copper.700'),
            '--tw-prose-bullets': theme('colors.stone.400'),
            '--tw-prose-hr': theme('colors.stone.200'),
            '--tw-prose-quotes': theme('colors.stone.800'),
            '--tw-prose-quote-borders': theme('colors.copper.600'),
            '--tw-prose-captions': theme('colors.stone.500'),
            '--tw-prose-code': theme('colors.copper.800'),
            '--tw-prose-pre-code': theme('colors.stone.200'),
            '--tw-prose-pre-bg': theme('colors.stone.900'),
            '--tw-prose-th-borders': theme('colors.stone.300'),
            '--tw-prose-td-borders': theme('colors.stone.200'),
            '--tw-prose-invert-body': theme('colors.stone.300'),
            '--tw-prose-invert-headings': theme('colors.stone.100'),
            '--tw-prose-invert-lead': theme('colors.stone.400'),
            '--tw-prose-invert-links': theme('colors.copper.400'),
            '--tw-prose-invert-bold': theme('colors.stone.100'),
            '--tw-prose-invert-counters': theme('colors.copper.400'),
            '--tw-prose-invert-bullets': theme('colors.stone.500'),
            '--tw-prose-invert-hr': theme('colors.stone.700'),
            '--tw-prose-invert-quotes': theme('colors.stone.200'),
            '--tw-prose-invert-quote-borders': theme('colors.copper.500'),
            '--tw-prose-invert-captions': theme('colors.stone.500'),
            '--tw-prose-invert-code': theme('colors.copper.300'),
            '--tw-prose-invert-pre-code': theme('colors.stone.300'),
            '--tw-prose-invert-pre-bg': theme('colors.stone.950'),
            '--tw-prose-invert-th-borders': theme('colors.stone.600'),
            '--tw-prose-invert-td-borders': theme('colors.stone.700'),
            'h2': {
              fontFamily: theme('fontFamily.display').join(', '),
              fontWeight: '400',
              letterSpacing: '-0.01em',
            },
            'h3': {
              fontFamily: theme('fontFamily.display').join(', '),
              fontWeight: '400',
            },
            'code': {
              fontFamily: theme('fontFamily.mono').join(', '),
              fontSize: '0.875em',
              fontWeight: '400',
            },
            'code::before': { content: '""' },
            'code::after': { content: '""' },
            'blockquote': {
              fontFamily: theme('fontFamily.display').join(', '),
              fontStyle: 'normal',
              fontWeight: '400',
              fontSize: '1.125em',
              borderLeftWidth: '2px',
            },
            'blockquote p:first-of-type::before': { content: '""' },
            'blockquote p:last-of-type::after': { content: '""' },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
